### ISSUE TITLE
Type Check Error in pow_test.py

### ISSUE THREAD

**Issue by eduardomadeira98** [alcides/aeon#2]
When testing the following program :

``` 
type Unit;
def math : Unit = native_import "math";
def test (b:{x:Float | 1 <= x <= 100}) -> (e:{y:Float | 1 <= y <= 100}) ->  Int { native "math.pow(b , e)"} 
```

it raises an Assertation error :
``` aeon/verification/horn.py:78: AssertionError ```

because the ```"type Unit;"``` is consider a `TypeVar`  instead of a `BaseType`

**Comment by alcides** [comment]
Can you try this with PR#3?

**Comment by eduardomadeira98** [comment]
That solved the problem about the import
I was getting another error and I thought that the syntax was wrong, but then I look to aeon_sugar.lark and the piece of code I was testing was syntactically correct 

I was trying :
```
type Unit;
        def math : Unit = native_import "math";
def test (b:{x:Float | 1 <= x && x <= 100}) ->
               (e:{y:Float | 1 <= y && y <= 100}) ->  Int { 
               native "lambda x: lambda y: math.pow(x , y)"
               } 
        ```
        Raised this error:
        
        ```eduardomadeira@MacBook-Pro-de-Eduardo aeon % python aeon examples/sugar/pow.ae   
(let math : Unit = (native_import "math") in
        (let test : (b:{ b:Float | ((b >= 1) && (b <= 100)) }) -> (e:{ e:Float | ((e >= 1) && (e <= 100)) }) -> Int = (\b -> (native "lambda x: lambda y: math.pow(x , y)")) in
        (print ?main)))

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/__main__.py", line 28, in <module>
    if check_type(ctx, p, top):
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/typechecking/typeinfer.py", line 267, in check_type
    return entailment(ctx, constraint)
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/typechecking/entailment.py", line 27, in entailment
    return entailment(ctx.prev, c)
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/typechecking/entailment.py", line 27, in entailment
    return entailment(ctx.prev, c)
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/typechecking/entailment.py", line 27, in entailment
    return entailment(ctx.prev, c)
  [Previous line repeated 11 more times]
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/typechecking/entailment.py", line 23, in entailment
    return solve(c)
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/verification/horn.py", line 334, in solve
    return smt_valid(c)
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/verification/smt.py", line 109, in smt_valid
    smt_c = translate(c, extra=forall_vars)
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/verification/smt.py", line 200, in translate
    e1 = translate_liq(c.pre, variables)
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/verification/smt.py", line 186, in translate_liq
    args = [translate_liq(a, variables) for a in t.args]
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/verification/smt.py", line 186, in <listcomp>
    args = [translate_liq(a, variables) for a in t.args]
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/verification/smt.py", line 186, in translate_liq
    args = [translate_liq(a, variables) for a in t.args]
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/verification/smt.py", line 186, in <listcomp>
    args = [translate_liq(a, variables) for a in t.args]
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/verification/smt.py", line 186, in translate_liq
    args = [translate_liq(a, variables) for a in t.args]
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/verification/smt.py", line 186, in <listcomp>
    args = [translate_liq(a, variables) for a in t.args]
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/verification/smt.py", line 187, in translate_liq
    return f(*args)
  File "/Users/eduardomadeira/Documents/lasige/aeon/aeon/verification/smt.py", line 47, in <lambda>
    ">=": lambda x, y: x >= y,
TypeError: '>=' not supported between instances of 'ExprRef' and 'int'
```

But then I tried using Int instead of Float like this:

        ```
        def test (b:{x:Int | 1 <= x && x <= 100}) ->
               (e:{y:Int | 1 <= y && y <= 100}) ->  Int { 
               native "lambda x: lambda y: math.pow(x , y)"
               } 
```
And it worked fine. I am now trying to figure out why its working with Int but not with Float

**Comment by eduardomadeira98** [comment]
smt.py does not import t_float, so smt.py doesn't handle floats yet, I will try to add that now
